export const ErrorCodes = {
  // Auth & Token
  INVALID_CREDENTIALS: 'ERR_INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'ERR_TOKEN_EXPIRED',
  TOKEN_REVOKED: 'ERR_TOKEN_REVOKED',
  TOKEN_INVALID: 'ERR_TOKEN_INVALID',
  TOKEN_MISSING: 'ERR_TOKEN_MISSING',
  UNAUTHORIZED: 'ERR_UNAUTHORIZED',
  FORBIDDEN: 'ERR_FORBIDDEN',

  // Validation
  VALIDATION_FAILED: 'ERR_VALIDATION_FAILED',

  // User
  USER_NOT_FOUND: 'ERR_USER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS: 'ERR_EMAIL_ALREADY_EXISTS',
  EMAIL_NOT_VERIFIED: 'ERR_EMAIL_NOT_VERIFIED',

  // System
  INTERNAL_ERROR: 'ERR_INTERNAL_ERROR',
  ROUTE_NOT_FOUND: 'ERR_ROUTE_NOT_FOUND',
} as const;
